name: Deployment

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: dotnet publish -o out --configuration Release
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      with:
        # FTP server name (you may need to specify a port)
        ftp_server: ${{ secrets.ftp_server }}
        # FTP account username
        ftp_username: ${{ secrets.ftp_username }}
        # FTP account password
        ftp_password: ${{ secrets.ftp_password }}
        local_dir: out
        # The remote folder to copy to, deafults to root FTP folder (I recommend you configure this on your server side instead of here)
        remote_dir: public_html
